# Generated by Django 3.2.3 on 2021-05-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0003_auto_20210528_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='something',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
